-- MySQL Script generated by MySQL Workbench
-- Sun Sep 23 17:39:59 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Lab_1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Lab_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Lab_1` DEFAULT CHARACTER SET utf8 ;
USE `Lab_1` ;

-- -----------------------------------------------------
-- Table `Lab_1`.`Passport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lab_1`.`Passport` ;

CREATE TABLE IF NOT EXISTS `Lab_1`.`Passport` (
  `Id` INT NOT NULL,
  `Series` VARCHAR(45) NOT NULL,
  `Number` VARCHAR(45) NOT NULL,
  `Was_Given_By` VARCHAR(45) NOT NULL,
  `Date_Of_Release` DATE NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lab_1`.`Marital_Status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lab_1`.`Marital_Status` ;

CREATE TABLE IF NOT EXISTS `Lab_1`.`Marital_Status` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lab_1`.`City`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lab_1`.`City` ;

CREATE TABLE IF NOT EXISTS `Lab_1`.`City` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lab_1`.`Disablity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lab_1`.`Disablity` ;

CREATE TABLE IF NOT EXISTS `Lab_1`.`Disablity` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lab_1`.`Citizenship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lab_1`.`Citizenship` ;

CREATE TABLE IF NOT EXISTS `Lab_1`.`Citizenship` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lab_1`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lab_1`.`Client` ;

CREATE TABLE IF NOT EXISTS `Lab_1`.`Client` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Second_Name` VARCHAR(45) NOT NULL,
  `Middle_Name` VARCHAR(45) NOT NULL,
  `Birth_Date` DATE NOT NULL,
  `Sex` ENUM("Male", "Female") NOT NULL,
  `Id_Number` VARCHAR(45) NOT NULL,
  `Birth_Place` VARCHAR(45) NOT NULL,
  `Address_Fact` VARCHAR(45) NOT NULL,
  `Home_Number` VARCHAR(45) NULL,
  `Work_Number` VARCHAR(45) NULL,
  `E_Mail` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Pensioner` TINYINT NOT NULL,
  `Monthly_Income` DOUBLE NULL,
  `War_Bound` TINYINT NOT NULL,
  `Marital_Status_Id` INT NOT NULL,
  `City_Id` INT NOT NULL,
  `Disablity_Id` INT NOT NULL,
  `Passport_Id` INT NOT NULL,
  `Citizenship_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `Marital_Status_Id`, `City_Id`, `Disablity_Id`, `Passport_Id`, `Citizenship_Id`),
  INDEX `fk_Client_Marital_Status_idx` (`Marital_Status_Id` ASC) VISIBLE,
  INDEX `fk_Client_City1_idx` (`City_Id` ASC) VISIBLE,
  INDEX `fk_Client_Disablity1_idx` (`Disablity_Id` ASC) VISIBLE,
  INDEX `fk_Client_Passport1_idx` (`Passport_Id` ASC) VISIBLE,
  INDEX `fk_Client_Citizenship1_idx` (`Citizenship_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Marital_Status`
    FOREIGN KEY (`Marital_Status_Id`)
    REFERENCES `Lab_1`.`Marital_Status` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_City1`
    FOREIGN KEY (`City_Id`)
    REFERENCES `Lab_1`.`City` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_Disablity1`
    FOREIGN KEY (`Disablity_Id`)
    REFERENCES `Lab_1`.`Disablity` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_Passport1`
    FOREIGN KEY (`Passport_Id`)
    REFERENCES `Lab_1`.`Passport` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_Citizenship1`
    FOREIGN KEY (`Citizenship_Id`)
    REFERENCES `Lab_1`.`Citizenship` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Lab_1` ;

-- -----------------------------------------------------
-- procedure getSortedListOFClients
-- -----------------------------------------------------

USE `Lab_1`;
DROP procedure IF EXISTS `Lab_1`.`getSortedListOFClients`;

DELIMITER $$
USE `Lab_1`$$
CREATE PROCEDURE `getSortedListOFClients` ()
BEGIN
	select *
    from Client
    order by Second_Name;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
