-- MySQL Script generated by MySQL Workbench
-- Sat Sep 22 19:34:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Lab_1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Lab_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Lab_1` DEFAULT CHARACTER SET utf8 ;
USE `Lab_1` ;

-- -----------------------------------------------------
-- Table `Lab_1`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lab_1`.`Client` ;

CREATE TABLE IF NOT EXISTS `Lab_1`.`Client` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Second_Name` VARCHAR(45) NULL,
  `Middle_Name` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
